<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Shops for Sale in Malaysia</name>
   <tag></tag>
   <elementGuidId>51c8b4c3-cd09-421c-b93d-2c093322f332</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[6]/div/div[4]/div/div[3]/div[2]/details[7]/ul/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>details.Shops-for-Sale > ul.seo-footer-ul > li > a.seo-footer-a-tag</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>33efe786-8869-48fa-8059-40384ca62df5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://sit.nextsix.com/properties-for-sale/malaysia/shop-office-retail-space</value>
      <webElementGuid>08efdcee-7f5c-48f7-aaa6-def84bae2aca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>seo-footer-a-tag</value>
      <webElementGuid>765c7a11-5338-40de-bc84-7844287c9fc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Shops for Sale in Malaysia</value>
      <webElementGuid>db969ee4-5d65-4462-a35d-c7d20e0efa1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;container&quot;]/div[@class=&quot;seo-footer&quot;]/div[4]/div[@class=&quot;seo-footer-row row&quot;]/div[@class=&quot;seo-footer-col col-12 col-md-6 col-lg-3&quot;]/div[@class=&quot;seo-footer-description&quot;]/details[@class=&quot;Shops-for-Sale&quot;]/ul[@class=&quot;seo-footer-ul&quot;]/li[1]/a[@class=&quot;seo-footer-a-tag&quot;]</value>
      <webElementGuid>87fe6a56-5aee-4ca8-963f-208b1ebbf2e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div[4]/div/div[3]/div[2]/details[7]/ul/li/a</value>
      <webElementGuid>996404ad-b227-4172-915d-89d6f511e653</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Shops for Sale in Malaysia')]</value>
      <webElementGuid>6e3efb8f-dca4-4dfb-84dd-e37248234033</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shops for Sale'])[1]/following::a[1]</value>
      <webElementGuid>437f110f-749b-43b6-984d-6aed636d5cee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Factories for Sale in Labuan'])[1]/following::a[1]</value>
      <webElementGuid>e1a9715e-dcee-44cd-9ea1-151cd5c4663a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shops for Sale in Selangor'])[1]/preceding::a[1]</value>
      <webElementGuid>597c0fcc-0f0f-40b2-90e9-1412aba033ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shops for Sale in Kuala Lumpur'])[1]/preceding::a[2]</value>
      <webElementGuid>b8058245-a475-455f-a11e-ea782050c81d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Shops for Sale in Malaysia']/parent::*</value>
      <webElementGuid>a52e1c8b-c854-4afc-8896-eb8e4eb36862</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://sit.nextsix.com/properties-for-sale/malaysia/shop-office-retail-space')]</value>
      <webElementGuid>54f9b967-f8a9-462a-8fff-8c85dea5fd04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//details[7]/ul/li/a</value>
      <webElementGuid>cfb7cc75-4a92-4c99-98d1-e1ca9906c89c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://sit.nextsix.com/properties-for-sale/malaysia/shop-office-retail-space' and (text() = 'Shops for Sale in Malaysia' or . = 'Shops for Sale in Malaysia')]</value>
      <webElementGuid>929ff633-de53-44a0-a957-b7f9a1de620f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
