<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Asialand Net</name>
   <tag></tag>
   <elementGuidId>60f54b2c-51e3-4677-b36e-35a04bd167ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#react-select-5-option-2 > label > span > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-5-option-2']/label/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>42bf695a-29a6-423f-b671-60340115b91d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Asialand Net</value>
      <webElementGuid>314e2f7d-47df-4fea-b4f3-1384a3c7d71e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-5-option-2&quot;)/label[1]/span[1]/span[1]</value>
      <webElementGuid>09d26cb1-50ac-4f4c-915f-86903152b234</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-select-5-option-2']/label/span/span</value>
      <webElementGuid>bfe928f4-09f0-462c-bb7c-65a32d2d320a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ork'])[1]/following::span[2]</value>
      <webElementGuid>04701759-766d-4e5a-8a5c-f9a2433a01de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='w'])[3]/following::span[3]</value>
      <webElementGuid>f1fb4c1b-3bde-41e8-a33d-61eba70c9f80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='w'])[4]/preceding::span[1]</value>
      <webElementGuid>b5e21384-45e2-4744-aa4e-a0a588dd8439</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ork (Pj)'])[1]/preceding::span[1]</value>
      <webElementGuid>194e9474-9eda-4df3-954a-ebfa41baef0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/label/span/span</value>
      <webElementGuid>d60cd617-56a7-4e2d-bbbe-024c6a5774a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Asialand Net' or . = 'Asialand Net')]</value>
      <webElementGuid>1dcedfb5-4e46-40c8-b9a4-50867664c850</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
