<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_New passwordConfirm new passwordNew pas_ac3c53</name>
   <tag></tag>
   <elementGuidId>492ff648-7e9f-4b6d-b00e-7dd142dde29d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.row</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>850e0db2-8b2f-48c8-88b3-6db86f63e987</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row</value>
      <webElementGuid>d8409b75-3371-438d-a9b6-bff89f838d0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>New passwordConfirm new passwordNew password and Confirm password do not match Submit</value>
      <webElementGuid>a703ab21-0c97-4da4-b21d-2bb7f3c3351c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;row&quot;]</value>
      <webElementGuid>e757258d-b8ff-4b3d-af11-7903eccac187</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div</value>
      <webElementGuid>b45545f7-e5de-430f-befe-529d1fc86e59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div</value>
      <webElementGuid>f4c0227b-c7f5-4db8-a3aa-4ab09c237c15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'New passwordConfirm new passwordNew password and Confirm password do not match Submit' or . = 'New passwordConfirm new passwordNew password and Confirm password do not match Submit')]</value>
      <webElementGuid>d7282f92-390e-4daf-b8bf-d49c7ab64e78</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
