<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>PropertyDetails-Sale</name>
   <tag></tag>
   <elementGuidId>e5785db4-86da-4316-b3b5-f2139d7ffd79</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  &quot;text&quot;: &quot;{\n  \&quot;id\&quot;:\&quot;63bcd42cd3d5170052169eab\&quot;,\n  \&quot;for\&quot;:\&quot;Buy\&quot;\n}&quot;,
  &quot;contentType&quot;: &quot;application/json&quot;,
  &quot;charset&quot;: &quot;UTF-8&quot;
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <httpHeaderProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>7e7cd257-38e5-4fab-b27d-bfebe07f5696</webElementGuid>
   </httpHeaderProperties>
   <katalonVersion>8.4.1</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <restRequestMethod>POST</restRequestMethod>
   <restUrl>https://sit-apps.nextsix.com/properties/byAgent</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>GlobalVariable.propertyName</defaultValue>
      <description></description>
      <id>9353f0e4-c597-4754-ab29-008d91dee98e</id>
      <masked>false</masked>
      <name>propertyName</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.propertyAddressArea</defaultValue>
      <description></description>
      <id>d42ef0bb-25ad-4a36-a1df-d92774db01ba</id>
      <masked>false</masked>
      <name>area</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.propertyAddressState</defaultValue>
      <description></description>
      <id>ea48a0cc-d526-4911-9a18-beebdaaf9076</id>
      <masked>false</masked>
      <name>state</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.propertyPrice</defaultValue>
      <description></description>
      <id>11fca097-7be6-4bc9-964b-62f6ee39e035</id>
      <masked>false</masked>
      <name>propertyPrice</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.propertyBed</defaultValue>
      <description></description>
      <id>1ca08d15-8408-4225-8755-c0c8cd387140</id>
      <masked>false</masked>
      <name>bed</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.propertyBath</defaultValue>
      <description></description>
      <id>ac1bf5f0-7955-4630-a8c9-789e3b5fddb2</id>
      <masked>false</masked>
      <name>bath</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.propertyCarPark</defaultValue>
      <description></description>
      <id>dde5ba0b-ca14-450f-b5fe-c0c28e17729f</id>
      <masked>false</masked>
      <name>carPark</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.propertyBuildUp</defaultValue>
      <description></description>
      <id>ff217f46-b66b-4511-bffd-af0931e7e663</id>
      <masked>false</masked>
      <name>buildUp</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.propertyUpdated</defaultValue>
      <description></description>
      <id>e7d7eaff-73c3-4b3e-a042-4605319921db</id>
      <masked>false</masked>
      <name>lastUpdated</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.propertyCreated</defaultValue>
      <description></description>
      <id>7b5d4507-b432-4f05-ab43-0043e185e30b</id>
      <masked>false</masked>
      <name>published</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.propertyAddress1</defaultValue>
      <description></description>
      <id>90960fd8-52fe-4266-9c83-6aafe5538b12</id>
      <masked>false</masked>
      <name>addressLine1</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.propertyPostcode</defaultValue>
      <description></description>
      <id>93c22283-2113-40b8-9758-22c2aeb64090</id>
      <masked>false</masked>
      <name>postcode</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.propertyHighlight</defaultValue>
      <description></description>
      <id>32e53e17-0332-4c7a-9a54-2e0660531bb5</id>
      <masked>false</masked>
      <name>highlight</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.propertyCategoryListing</defaultValue>
      <description></description>
      <id>cd4a0ac5-eee4-443e-b8b0-30438fdf75da</id>
      <masked>false</masked>
      <name>propertyCategory</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.propertyTitle</defaultValue>
      <description></description>
      <id>20548ee6-8fc5-4fc1-a295-be0b8087582f</id>
      <masked>false</masked>
      <name>propertyTitle</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.propertyTenure</defaultValue>
      <description></description>
      <id>719e9221-1e37-4148-b5b4-336a902171a6</id>
      <masked>false</masked>
      <name>propertyTenure</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.propertyFurnishing</defaultValue>
      <description></description>
      <id>0a33c48d-5d55-41b3-9c85-1a7aa2371a21</id>
      <masked>false</masked>
      <name>propertyFurnishing</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.propertyDirection</defaultValue>
      <description></description>
      <id>735c2b4a-cb52-4f8e-8eb3-9915bf2ddb39</id>
      <masked>false</masked>
      <name>propertyDirection</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.propertyOccupied</defaultValue>
      <description></description>
      <id>01aee810-91ca-44c8-a692-655bb82136e7</id>
      <masked>false</masked>
      <name>propertyOccupied</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.propertyUnitType</defaultValue>
      <description></description>
      <id>a8fc1e61-101d-499c-ac50-1a7fd22ca6d7</id>
      <masked>false</masked>
      <name>propertyUnitType</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.propertyDescription</defaultValue>
      <description></description>
      <id>2a105f42-4a06-4435-924f-70ec93745338</id>
      <masked>false</masked>
      <name>propertyDescription</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.propertyFacilities0</defaultValue>
      <description></description>
      <id>d12d027b-2cfc-4293-8e54-75b13677e6c2</id>
      <masked>false</masked>
      <name>facilities0</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.memo</defaultValue>
      <description></description>
      <id>96512422-0923-46ef-b9c6-b14d4b714d4a</id>
      <masked>false</masked>
      <name>memo</name>
   </variables>
   <verificationScript>import static org.assertj.core.api.Assertions.*

import com.kms.katalon.core.testobject.RequestObject
import com.kms.katalon.core.testobject.ResponseObject
import com.kms.katalon.core.webservice.keyword.WSBuiltInKeywords as WS
import com.kms.katalon.core.webservice.verification.WSResponseManager

import groovy.json.JsonSlurper
import internal.GlobalVariable as GlobalVariable

RequestObject request = WSResponseManager.getInstance().getCurrentRequest()

ResponseObject response = WSResponseManager.getInstance().getCurrentResponse()</verificationScript>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
