<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_NextSix</name>
   <tag></tag>
   <elementGuidId>71b5c410-45ee-4bf4-9db8-ba6d7e2a0f09</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;648dd9bb-7155-2a5e-9e72-9f7544a792ee&quot;)/div[1]/div[@class=&quot;zKDWD YbB6r IKvQi IjQyD JCRRb cSOXK G1NES&quot;]/div[@class=&quot;XG5Jd JtO0E&quot;]/div[@class=&quot;S2NDX&quot;]/div[@class=&quot;KKAj0 XG5Jd&quot;]/div[@class=&quot;gMkyO gy2aJ Dc0o9 Ejrkd&quot;]/span[1][count(. | //span[@title = 'support@nextsix.com']) = count(//span[@title = 'support@nextsix.com'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span[title=&quot;support@nextsix.com&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='648dd9bb-7155-2a5e-9e72-9f7544a792ee']/div/div/div/div[2]/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3f7fd481-5fb6-4e93-9964-5db17340a201</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>support@nextsix.com</value>
      <webElementGuid>0896aefe-a90e-4615-b09e-7c730997e80a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NextSix</value>
      <webElementGuid>a4b6d365-40d1-43b8-8dc9-92a1435667a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;648dd9bb-7155-2a5e-9e72-9f7544a792ee&quot;)/div[1]/div[@class=&quot;zKDWD YbB6r IKvQi IjQyD JCRRb cSOXK G1NES&quot;]/div[@class=&quot;XG5Jd JtO0E&quot;]/div[@class=&quot;S2NDX&quot;]/div[@class=&quot;KKAj0 XG5Jd&quot;]/div[@class=&quot;gMkyO gy2aJ Dc0o9 Ejrkd&quot;]/span[1]</value>
      <webElementGuid>3de756c5-e56c-4024-b337-b087e336ef62</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='648dd9bb-7155-2a5e-9e72-9f7544a792ee']/div/div/div/div[2]/div/div/span</value>
      <webElementGuid>0a84a0e2-dd0d-47d1-915a-bfad88528c70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='N'])[1]/following::span[1]</value>
      <webElementGuid>3f1c139e-ce3c-4d12-8d85-c14e596f8bd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Top results'])[1]/following::span[2]</value>
      <webElementGuid>46ec01e3-77d3-4657-a836-bfcbc36602ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reset'])[1]/preceding::span[7]</value>
      <webElementGuid>2ab1f5b8-8a6d-4c2f-b2b7-0661d107f087</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='your'])[1]/preceding::span[8]</value>
      <webElementGuid>c4244e16-c0bd-49f0-9b26-c501b36e6eb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='NextSix']/parent::*</value>
      <webElementGuid>f4756243-a849-4570-9179-9eea2267df74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/div/div[2]/div/div/span</value>
      <webElementGuid>b86e5d48-31ba-46f8-8ad6-cc772eb91455</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'support@nextsix.com' and (text() = 'NextSix' or . = 'NextSix')]</value>
      <webElementGuid>b1f30784-3dda-4bf9-ad84-01967fa5b3bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
