<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Skip to main content_O365_MainLink_NavMenu</name>
   <tag></tag>
   <elementGuidId>6ddd0193-38bc-4606-a353-0f0eb88e827c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#O365_MainLink_NavMenu</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='O365_MainLink_NavMenu']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>19786fc9-8e4e-454a-9c5f-7062a24fbc8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>O365_MainLink_NavMenu</value>
      <webElementGuid>485f4247-4975-4582-b659-6a986896c5db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_2sngRVSfiZnZSR2_elJ0bG o365sx-button o365sx-waffle </value>
      <webElementGuid>239bef2e-cf39-4ae6-b471-f5206e1613c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>262576ba-1d19-4d39-96ff-1f9e2e693379</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a1359744-94e5-4b72-9f2a-c1147f9c0cf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0c47b5cb-a8d9-40e6-a45d-783c03510deb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f8bdcc14-bbf9-4ca2-ba4d-21828d550171</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>App launcher</value>
      <webElementGuid>4688430b-8b0a-4d78-99ea-4ebf3536a73d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>App launcher</value>
      <webElementGuid>c409f7c0-ed11-4389-9df8-5527c1ecae42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;O365_MainLink_NavMenu&quot;)</value>
      <webElementGuid>9de81ef9-bf72-423b-af66-2b1843f4608a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='O365_MainLink_NavMenu']</value>
      <webElementGuid>745b3ead-5f27-4b57-922a-eb5b02e08c5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='O365_HeaderLeftRegion']/div/button</value>
      <webElementGuid>f9281972-7ba2-4bcf-9796-3ec6dd1e9b11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skip to main content'])[1]/following::button[1]</value>
      <webElementGuid>41e435aa-a8b1-460f-83fe-4c3039969111</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn how'])[1]/following::button[2]</value>
      <webElementGuid>3f3ced59-cc33-4e49-810c-6ea1fab08b08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Microsoft account'])[1]/preceding::button[1]</value>
      <webElementGuid>b5cf8d37-8132-4d0a-b5c8-5f1743cf0545</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your info'])[1]/preceding::button[1]</value>
      <webElementGuid>4f7f797a-8215-4120-b0e7-a91719376741</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/button</value>
      <webElementGuid>813e79dd-1c38-4da9-a085-1678e3cd6ec4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'O365_MainLink_NavMenu' and @type = 'button' and @title = 'App launcher']</value>
      <webElementGuid>f466ef45-9bf3-445d-9909-446f681a46a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
