<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Terrace Houses for Sale in Kedah</name>
   <tag></tag>
   <elementGuidId>81586f1c-57e0-40b4-8c1f-b2fafac0220e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[6]/div/div[4]/div/div[3]/div[2]/details[4]/ul/li[10]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>64e534a2-a561-44c2-bed7-1d4b66d2c892</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://sit.nextsix.com/properties-for-sale/kedah/terrace-link-townhouse</value>
      <webElementGuid>b1799677-cda3-4030-b24f-aa3742e487f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>seo-footer-a-tag</value>
      <webElementGuid>bc569d52-627a-439a-b51b-40bd4705c51f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Terrace Houses for Sale in Kedah</value>
      <webElementGuid>fa46d5f9-28a3-41cf-8bca-6ebdb91ddb7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;container&quot;]/div[@class=&quot;seo-footer&quot;]/div[4]/div[@class=&quot;seo-footer-row row&quot;]/div[@class=&quot;seo-footer-col col-12 col-md-6 col-lg-3&quot;]/div[@class=&quot;seo-footer-description&quot;]/details[@class=&quot;Terrace-Houses-for-Sale&quot;]/ul[@class=&quot;seo-footer-ul&quot;]/li[10]/a[@class=&quot;seo-footer-a-tag&quot;]</value>
      <webElementGuid>50a8e02f-af42-4751-b45f-cb15c2104a60</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div[4]/div/div[3]/div[2]/details[4]/ul/li[10]/a</value>
      <webElementGuid>e260374a-39b6-42e8-a775-ba54bbcbd517</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Terrace Houses for Sale in Kedah')]</value>
      <webElementGuid>0eedd4a5-2478-4344-9b93-77f2dcb7701b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terrace Houses for Sale in Sarawak'])[1]/following::a[1]</value>
      <webElementGuid>3d6bf7bd-b012-47b4-a3f5-b07be49f8c93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terrace Houses for Sale in Negeri Sembilan'])[1]/following::a[2]</value>
      <webElementGuid>4c3c86d9-17bc-453c-b237-fe81873ba330</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terrace Houses for Sale in Kelantan'])[1]/preceding::a[1]</value>
      <webElementGuid>bf5ee833-d0f6-4514-a776-3a613b166bcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terrace Houses for Sale in Pahang'])[1]/preceding::a[2]</value>
      <webElementGuid>22095d67-bcd8-414d-95df-dbc15beca843</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Terrace Houses for Sale in Kedah']/parent::*</value>
      <webElementGuid>9b675a4f-c294-44e6-aedd-aaf6a97436d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://sit.nextsix.com/properties-for-sale/kedah/terrace-link-townhouse')]</value>
      <webElementGuid>5f1226c1-b80d-4de8-99a6-1821d807537d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//details[4]/ul/li[10]/a</value>
      <webElementGuid>03524157-9e07-4609-ac9b-25e1dcb64992</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://sit.nextsix.com/properties-for-sale/kedah/terrace-link-townhouse' and (text() = 'Terrace Houses for Sale in Kedah' or . = 'Terrace Houses for Sale in Kedah')]</value>
      <webElementGuid>e15c7321-cdfc-45b7-aeec-36bffc001957</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
