<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Terrace Houses for Sale in Kelantan</name>
   <tag></tag>
   <elementGuidId>e3de781f-552e-49be-8abe-a1b4819fae2b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[6]/div/div[4]/div/div[3]/div[2]/details[4]/ul/li[11]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b956a2f5-62e6-4fca-9acc-8e5edfb45d60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://sit.nextsix.com/properties-for-sale/kelantan/terrace-link-townhouse</value>
      <webElementGuid>af367748-91d9-49bb-b030-ad87773f3cca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>seo-footer-a-tag</value>
      <webElementGuid>b947addc-dd05-4d10-ba2c-d34551b2fdcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Terrace Houses for Sale in Kelantan</value>
      <webElementGuid>ea6a028f-559e-456f-b4d8-a72244a6df8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;container&quot;]/div[@class=&quot;seo-footer&quot;]/div[4]/div[@class=&quot;seo-footer-row row&quot;]/div[@class=&quot;seo-footer-col col-12 col-md-6 col-lg-3&quot;]/div[@class=&quot;seo-footer-description&quot;]/details[@class=&quot;Terrace-Houses-for-Sale&quot;]/ul[@class=&quot;seo-footer-ul&quot;]/li[11]/a[@class=&quot;seo-footer-a-tag&quot;]</value>
      <webElementGuid>7f19cb5e-06c8-4d5e-b839-2ae5a90aa837</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div[4]/div/div[3]/div[2]/details[4]/ul/li[11]/a</value>
      <webElementGuid>c51219d3-8871-49a0-bb16-288824517a53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Terrace Houses for Sale in Kelantan')]</value>
      <webElementGuid>5ccf976d-647e-4560-9154-8dbe197f76eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terrace Houses for Sale in Kedah'])[1]/following::a[1]</value>
      <webElementGuid>de8413a0-113f-4242-961d-c9bdcd94ffb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terrace Houses for Sale in Sarawak'])[1]/following::a[2]</value>
      <webElementGuid>fc20f54c-8bd3-457a-b29d-c5e2ffa17f71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terrace Houses for Sale in Pahang'])[1]/preceding::a[1]</value>
      <webElementGuid>a5bb142d-c0fc-453d-b7b3-e16eafc0687c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terrace Houses for Sale in Perak'])[1]/preceding::a[2]</value>
      <webElementGuid>4b2c8930-e348-45b1-a60d-08bf82354afb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Terrace Houses for Sale in Kelantan']/parent::*</value>
      <webElementGuid>88aff075-bf0e-42d6-8366-924e6ba72385</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://sit.nextsix.com/properties-for-sale/kelantan/terrace-link-townhouse')]</value>
      <webElementGuid>d88bac9d-7e60-4c43-9008-c3810e59854a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//details[4]/ul/li[11]/a</value>
      <webElementGuid>3ba85e58-557e-4e9a-a39b-c2a6c78134bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://sit.nextsix.com/properties-for-sale/kelantan/terrace-link-townhouse' and (text() = 'Terrace Houses for Sale in Kelantan' or . = 'Terrace Houses for Sale in Kelantan')]</value>
      <webElementGuid>4b87cf82-8deb-43ab-ad78-000d82a78d6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
