<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Terrace Houses for Sale in Sarawak</name>
   <tag></tag>
   <elementGuidId>ee4a03fe-db56-44b4-9759-839249c94d8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[6]/div/div[4]/div/div[3]/div[2]/details[4]/ul/li[9]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ac308647-2aeb-4e66-9cb6-146feb8a988d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://sit.nextsix.com/properties-for-sale/sarawak/terrace-link-townhouse</value>
      <webElementGuid>b118db42-6899-4a09-a8e0-40d7e880d29a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>seo-footer-a-tag</value>
      <webElementGuid>3fc3ec8d-63a6-441b-9a99-538b6581cb41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Terrace Houses for Sale in Sarawak</value>
      <webElementGuid>957e9e63-feaf-4782-8973-13622c18a351</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;container&quot;]/div[@class=&quot;seo-footer&quot;]/div[4]/div[@class=&quot;seo-footer-row row&quot;]/div[@class=&quot;seo-footer-col col-12 col-md-6 col-lg-3&quot;]/div[@class=&quot;seo-footer-description&quot;]/details[@class=&quot;Terrace-Houses-for-Sale&quot;]/ul[@class=&quot;seo-footer-ul&quot;]/li[9]/a[@class=&quot;seo-footer-a-tag&quot;]</value>
      <webElementGuid>5e30629d-9810-4c87-8468-8caa0a3d00b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div[4]/div/div[3]/div[2]/details[4]/ul/li[9]/a</value>
      <webElementGuid>d4bf1eeb-75dc-47c4-ad6b-8e7d52dd7dc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Terrace Houses for Sale in Sarawak')]</value>
      <webElementGuid>6ca27ada-fd2e-4866-bf7c-523402c50a29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terrace Houses for Sale in Negeri Sembilan'])[1]/following::a[1]</value>
      <webElementGuid>d0761285-30cf-4151-9151-d6a5dfa8542d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terrace Houses for Sale in Melaka'])[1]/following::a[2]</value>
      <webElementGuid>2918d648-2773-4e8c-954e-24ead37eb997</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terrace Houses for Sale in Kedah'])[1]/preceding::a[1]</value>
      <webElementGuid>14804181-0bad-439d-8736-4605629e4e70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terrace Houses for Sale in Kelantan'])[1]/preceding::a[2]</value>
      <webElementGuid>624ee2da-1966-408e-a0e9-3bc34b341fd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Terrace Houses for Sale in Sarawak']/parent::*</value>
      <webElementGuid>5a197549-2565-4759-b547-7f8b3743253d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://sit.nextsix.com/properties-for-sale/sarawak/terrace-link-townhouse')]</value>
      <webElementGuid>d50de7c0-563e-4e4a-b1a1-fd306d50235b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//details[4]/ul/li[9]/a</value>
      <webElementGuid>1f9c9886-305e-4a7f-8434-e2ec3d4f8adb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://sit.nextsix.com/properties-for-sale/sarawak/terrace-link-townhouse' and (text() = 'Terrace Houses for Sale in Sarawak' or . = 'Terrace Houses for Sale in Sarawak')]</value>
      <webElementGuid>f80de0ab-d7eb-473c-abec-ae3b5089cec0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
