<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Terrace Houses for Rent in Perak</name>
   <tag></tag>
   <elementGuidId>b4c55d6a-28fb-4704-be67-27cf6ebbb405</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[6]/div/div[4]/div/div[4]/div[2]/details[4]/ul/li[13]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0b47d976-7d72-451b-8031-184a93c174d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>seo-footer-a-tag</value>
      <webElementGuid>ffa71ec5-8d87-45ae-a48e-5ac5a4448882</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://sit.nextsix.com/properties-for-rent/perak/terrace-link-townhouse</value>
      <webElementGuid>8e83007a-07c9-4005-93d1-3510b762643e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Terrace Houses for Rent in Perak</value>
      <webElementGuid>38f36d5a-c1b4-4959-b3f1-94f5786559dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;container&quot;]/div[@class=&quot;seo-footer&quot;]/div[4]/div[@class=&quot;seo-footer-row row&quot;]/div[@class=&quot;seo-footer-col col-12 col-md-6 col-lg-3&quot;]/div[@class=&quot;seo-footer-description&quot;]/details[@class=&quot;Terrace-Houses-for-Rent&quot;]/ul[@class=&quot;seo-footer-ul&quot;]/li[13]/a[@class=&quot;seo-footer-a-tag&quot;]</value>
      <webElementGuid>2418ab56-fd90-4499-bfef-99f3556b04f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[6]/div/div[4]/div/div[4]/div[2]/details[4]/ul/li[13]/a</value>
      <webElementGuid>fb6d4364-06f8-4dbf-8667-e9a6ee1709cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Terrace Houses for Rent in Perak')]</value>
      <webElementGuid>fbd2321b-b7c9-4d58-a3f8-8cb515b7cb50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terrace Houses for Rent in Pahang'])[1]/following::a[1]</value>
      <webElementGuid>7711e8e6-0c1b-4ac2-add3-cfcc3416947f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terrace Houses for Rent in Kelantan'])[1]/following::a[2]</value>
      <webElementGuid>8bdfc5a5-5db5-4dd6-aad4-ffa143fbef7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terrace Houses for Rent in Perlis'])[1]/preceding::a[1]</value>
      <webElementGuid>062f89b3-c288-4be6-ac10-cc44df00db2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terrace Houses for Rent in Sabah'])[1]/preceding::a[2]</value>
      <webElementGuid>a14b17a2-e745-4b70-aadf-99780306701a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Terrace Houses for Rent in Perak']/parent::*</value>
      <webElementGuid>f21dd061-dbb6-4b15-9b9d-34129d844ff4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://sit.nextsix.com/properties-for-rent/perak/terrace-link-townhouse')]</value>
      <webElementGuid>439de14c-eb25-4514-8a09-e4186878dccb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//details[4]/ul/li[13]/a</value>
      <webElementGuid>d4e2791c-cb75-440a-b6a5-88e46b0dfa1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://sit.nextsix.com/properties-for-rent/perak/terrace-link-townhouse' and (text() = 'Terrace Houses for Rent in Perak' or . = 'Terrace Houses for Rent in Perak')]</value>
      <webElementGuid>961d5850-d8f9-4875-ae91-822c6ab02053</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
