<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Sign out</name>
   <tag></tag>
   <elementGuidId>c5148a4e-67e0-4bae-8ae7-90b7d35ee03b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='mectrl_body_signOut']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mectrl_body_signOut</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b6e86b18-9f32-4ebb-9ce7-0051e2033170</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mectrl_body_signOut</value>
      <webElementGuid>1924907c-1704-4242-a8e2-2f8c312f91b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mectrl_resetStyle mectrl_signout mectrl_truncate</value>
      <webElementGuid>21d2fb64-3aee-4cba-a148-eb65ae9d1349</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Sign out of this account</value>
      <webElementGuid>1082c742-1664-4767-b239-4198a72aad6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d053c6e5-80c5-4649-9fb8-d4aaa7758aad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://login.microsoftonline.com/common/oauth2/v2.0/logout?post_logout_redirect_uri=https%3A%2F%2Faccount.microsoft.com%2Fauth%2Fcomplete-signout-oauth&amp;logout_hint=M%24EjZ4nOPY1f3_bPOi3QdChMRLUotLUovyUitKzBzyS0ty8vOz9ZLzcyUmHH22_Nd_IGAEAASSF24&amp;ru=https%3A%2F%2Faccount.microsoft.com%2F%3Flang%3Den-US%26refd%3Daccount.live.com%26refp%3Dlanding%26mkt%3DEN-US</value>
      <webElementGuid>5c5a9ec4-6f0a-49cb-9be3-37f74834d5ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_top</value>
      <webElementGuid>54183367-7cd4-4e29-83be-d0ac95e4d7bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign out</value>
      <webElementGuid>b8a7970a-0ee4-49f9-9780-c102a306bdf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mectrl_body_signOut&quot;)</value>
      <webElementGuid>34314db8-748f-4d9d-b755-074dae7f7ef2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='mectrl_body_signOut']</value>
      <webElementGuid>045c1785-6aed-4d00-a7a9-75a868f6ba7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mectrl_main_body']/div/div/a</value>
      <webElementGuid>e5c42b5c-1fe6-49ca-9b39-020ea67f45b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Sign out')]</value>
      <webElementGuid>46ab27cc-4f82-4cfe-9856-7807e1de4d74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My profile'])[1]/following::a[1]</value>
      <webElementGuid>0e9c8390-f66a-49fb-b155-a6e3e7bfd49b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Review and manage your Microsoft account information'])[1]/following::a[2]</value>
      <webElementGuid>81f49c58-dbe4-4eec-ac84-5f45f141fc46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in with a different account'])[1]/preceding::a[1]</value>
      <webElementGuid>34f54c10-0a9b-428d-bcc7-1ccadc7aceb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='tester next6'])[3]/preceding::a[3]</value>
      <webElementGuid>152650d7-e001-41ec-96e5-3e1844d358b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sign out']/parent::*</value>
      <webElementGuid>a17c47e6-8f97-4baa-aa99-67754ad4b042</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://login.microsoftonline.com/common/oauth2/v2.0/logout?post_logout_redirect_uri=https%3A%2F%2Faccount.microsoft.com%2Fauth%2Fcomplete-signout-oauth&amp;logout_hint=M%24EjZ4nOPY1f3_bPOi3QdChMRLUotLUovyUitKzBzyS0ty8vOz9ZLzcyUmHH22_Nd_IGAEAASSF24&amp;ru=https%3A%2F%2Faccount.microsoft.com%2F%3Flang%3Den-US%26refd%3Daccount.live.com%26refp%3Dlanding%26mkt%3DEN-US')]</value>
      <webElementGuid>58b0da99-0782-430a-8fa7-669feb6a3734</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/a</value>
      <webElementGuid>c2ce0803-7237-40ea-8ccf-3ee2967608a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'mectrl_body_signOut' and @href = 'https://login.microsoftonline.com/common/oauth2/v2.0/logout?post_logout_redirect_uri=https%3A%2F%2Faccount.microsoft.com%2Fauth%2Fcomplete-signout-oauth&amp;logout_hint=M%24EjZ4nOPY1f3_bPOi3QdChMRLUotLUovyUitKzBzyS0ty8vOz9ZLzcyUmHH22_Nd_IGAEAASSF24&amp;ru=https%3A%2F%2Faccount.microsoft.com%2F%3Flang%3Den-US%26refd%3Daccount.live.com%26refp%3Dlanding%26mkt%3DEN-US' and (text() = 'Sign out' or . = 'Sign out')]</value>
      <webElementGuid>342dd8a0-bf2c-49c0-8f11-9be6dd1599b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
