<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Developer Sales Form</name>
   <tag></tag>
   <elementGuidId>d21db18d-8c58-439f-83ab-484c4bd6d4d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/a[3]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d4a55417-87b3-49de-9190-b476ba8f79fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>side-drawer-navLink-single</value>
      <webElementGuid>8fce5760-6f2e-46ca-9b61-835b724349f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Developer Sales Form</value>
      <webElementGuid>d3f82863-da05-47c8-8e35-539a887a0928</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;side-drawer open&quot;]/div[@class=&quot;side-drawer-body&quot;]/a[@class=&quot;side-drawer-main-single&quot;]/div[@class=&quot;side-drawer-navLink-single&quot;]</value>
      <webElementGuid>8d12abc1-1c1a-488b-aefa-87cd20ffb106</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/a[3]/div</value>
      <webElementGuid>3b0dbe86-ad15-45c0-8f04-6e6d4f41dc79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='rent cum receipt form'])[1]/following::div[2]</value>
      <webElementGuid>b08941cc-304d-4e39-8e1d-2c9d58664e36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='secure rent form'])[1]/following::div[2]</value>
      <webElementGuid>0d95e6c9-adee-4ef1-8dad-6bb83eaa607d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Claim Submission Form'])[1]/preceding::div[2]</value>
      <webElementGuid>ad0147b2-ece0-41ee-9082-00efbd3184ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Official Receipt'])[1]/preceding::div[4]</value>
      <webElementGuid>bcc12815-9c6b-4f61-a399-2d0ed24af36a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Developer Sales Form']/parent::*</value>
      <webElementGuid>db02b8bc-7f7e-489c-9683-ec8c90b80274</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]/div</value>
      <webElementGuid>93fff4fc-44fa-46eb-8a06-94c5771ceedb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Developer Sales Form' or . = 'Developer Sales Form')]</value>
      <webElementGuid>83695c2a-0958-4c1a-abfe-42f8e691d8aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
