<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__DeveloperSalesProjectName</name>
   <tag></tag>
   <elementGuidId>515ce4ab-f614-406c-b08d-2bc14ae058fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='DeveloperSalesProjectName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;DeveloperSalesProjectName&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2e59c2c1-e69a-4456-81d8-28f650899925</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DeveloperSalesProjectName</value>
      <webElementGuid>f3eadb4a-e831-45ff-9336-af5384c97651</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Project Name</value>
      <webElementGuid>7914ce58-c622-4e8e-8da6-8979719c2301</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8187d46a-50bc-4304-9043-1e92a0220a36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>be4cf3d0-6378-4e31-8048-c7c12a8b214b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;cr-page admin-wrapper&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;mb-3 row&quot;]/div[@class=&quot;col-12 col-sm-4 col-md-4 col-lg-4&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>b0996670-d464-4fd7-a286-301ea17344d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='DeveloperSalesProjectName']</value>
      <webElementGuid>2e679490-cd64-4500-88ab-2ec1c19c61aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div[2]/div[2]/div[2]/input</value>
      <webElementGuid>43b5488b-36a5-40ad-aacd-c510d40b0502</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>da820a56-0c99-4eda-8702-c8ccfa647583</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'DeveloperSalesProjectName' and @placeholder = 'Project Name' and @type = 'text']</value>
      <webElementGuid>580f9b6d-8157-4f1f-b633-a6364d5a66eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
