<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__DeveloperSalesSPAPrice</name>
   <tag></tag>
   <elementGuidId>eaec79b6-c290-4d5b-b4fb-035a6374bed4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='DeveloperSalesSPAPrice']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;DeveloperSalesSPAPrice&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c5a1528f-03e7-470d-bca0-43bb3a4e38a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DeveloperSalesSPAPrice</value>
      <webElementGuid>bfd105ef-8b91-470e-bf76-a666d9ae9c22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>SPA Price (RM)</value>
      <webElementGuid>8b15737d-87a8-4f13-b18a-a5d115ab594f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8ad5a1f6-cdf3-41bb-8086-fe7237d5e478</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d0378da0-64cf-4267-987d-de70eb4d1d3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;cr-page admin-wrapper&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;mb-3 row&quot;]/div[@class=&quot;col-12 col-sm-4 col-md-4 col-lg-4&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>77cb0224-9e4d-40f4-97ea-948e5953b2e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='DeveloperSalesSPAPrice']</value>
      <webElementGuid>be7f492e-e2db-4740-9df6-0ee102342f4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div[2]/div[18]/div[3]/input</value>
      <webElementGuid>bdc264c1-d483-4b5b-a522-2a16e5e620c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[18]/div[3]/input</value>
      <webElementGuid>e457331d-c158-4c84-b129-7f312e004724</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'DeveloperSalesSPAPrice' and @placeholder = 'SPA Price (RM)' and @type = 'text']</value>
      <webElementGuid>d010ea14-dfba-4f74-b2d2-54724bd79270</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
