<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__DeveloperSalesAgentCommission</name>
   <tag></tag>
   <elementGuidId>0224b7d6-f449-40c5-b7fb-1db3831464ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='DeveloperSalesAgentCommission']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;DeveloperSalesAgentCommission&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>62e7c77c-5ea0-4d0d-a018-4ce2567738ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DeveloperSalesAgentCommission</value>
      <webElementGuid>418d320a-020c-4479-b93c-b7914bfa95ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Commission (RM)</value>
      <webElementGuid>8e9f36f3-bac3-4fff-ac08-593d09277f5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ba981768-59a2-4df4-9ce4-778abed3b678</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e62f125c-4aff-4035-adc2-ae28a37f18c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;cr-page admin-wrapper&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;mb-3 row&quot;]/div[@class=&quot;col-12 col-sm-6 col-md-6 col-lg-6&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>55815e58-3bb0-48c7-9196-9ca195ef0801</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='DeveloperSalesAgentCommission']</value>
      <webElementGuid>66e2070f-d1d2-46e8-a7b1-5492c532ac35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div[2]/div[22]/div/input</value>
      <webElementGuid>5e865cb8-d59d-4f13-97a1-db6f413b8e05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[22]/div/input</value>
      <webElementGuid>50528d80-5278-467e-9c35-35df50834529</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'DeveloperSalesAgentCommission' and @placeholder = 'Commission (RM)' and @type = 'text']</value>
      <webElementGuid>fd3ea1e9-a455-4f1a-85c7-77c11ddd8e1d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
