<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Active</name>
   <tag></tag>
   <elementGuidId>c80395a1-529b-49a7-8332-338b897d41ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.selection-input-label.col-sm-12.col-xl-2.col-form-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div/div/div[2]/div[2]/div[3]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>6d39c316-fed9-470e-94ad-e601263f5ef7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>active</value>
      <webElementGuid>0abb05f4-870c-4a51-8664-099f6d4b7095</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selection-input-label col-sm-12 col-xl-2 col-form-label</value>
      <webElementGuid>6bf39132-5656-46b7-b931-dbdcc8a5f5f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Active :</value>
      <webElementGuid>1427e4f7-8998-4a39-81d3-f273984f2a88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;cr-app bg-light&quot;]/div[@class=&quot;cr-content container-fluid&quot;]/div[@class=&quot;cr-page px-3&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;row form-group&quot;]/label[@class=&quot;selection-input-label col-sm-12 col-xl-2 col-form-label&quot;]</value>
      <webElementGuid>d9c0dbe4-a2ac-4e3b-bb9f-95b99100c118</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div/div[2]/div[2]/div[3]/label</value>
      <webElementGuid>865f290f-1cbc-47eb-a76c-ee3065f05414</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pending'])[1]/following::label[1]</value>
      <webElementGuid>e3963371-92df-41ec-b3d3-e1a7949c8e2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Online Hours'])[2]/following::label[1]</value>
      <webElementGuid>fcdc6cd0-9abb-4332-93b2-3a5c1e1b3c46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Personal Details'])[1]/preceding::label[1]</value>
      <webElementGuid>596c0f7b-8727-4ae3-85f2-fd8308e684d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>c78fab07-5874-4647-b0ef-bec7e2d61184</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Active :' or . = 'Active :')]</value>
      <webElementGuid>a09f747f-610a-4027-acd7-0567ab6146af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
