<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Select Gender</name>
   <tag></tag>
   <elementGuidId>871e2d0d-f625-40dc-aea6-8425231cbd5f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[204]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d9563242-213b-4d95-807f-7eec9e4513b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>96f86239-68c2-4f48-95fb-dbd4cde790c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3b1a73c1-5451-4468-b10d-770b3d18685b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c2dfded1-a461-4fb7-956f-25b33186a0ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-capitalize-dropdown-toggle-pvpage m-1 dropdown-toggle btn btn-transparent btn-m</value>
      <webElementGuid>6ae2d960-8c91-411f-a4be-08c0bf9decc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Gender*</value>
      <webElementGuid>9007de92-be2a-4cb5-8a7d-af7c8bb10a60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;the-will-background&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-8 col-sm-6 col-md-4 col-lg-4&quot;]/div[@class=&quot;btn-group&quot;]/span[@class=&quot;dd-drop-select&quot;]/button[@class=&quot;text-capitalize-dropdown-toggle-pvpage m-1 dropdown-toggle btn btn-transparent btn-m&quot;]</value>
      <webElementGuid>a42f05f0-578a-45a0-ac9e-a4c4b55fc8a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[204]</value>
      <webElementGuid>2ec5804c-0d4a-4365-ac00-255135c94c3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div[6]/div[2]/div/span/button</value>
      <webElementGuid>62ec7a78-309a-4a7a-8aa7-e3c3a64e6174</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/following::button[1]</value>
      <webElementGuid>6bfb3875-0f46-4a45-82bb-b9ef3717895e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='male'])[1]/preceding::button[1]</value>
      <webElementGuid>ff72a954-707f-4a91-9a90-ac6be199f5c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div/span/button</value>
      <webElementGuid>2caf3b4c-ed43-43c2-bfc6-fc5f0f1aae69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Select Gender*' or . = 'Select Gender*')]</value>
      <webElementGuid>bcb90e3a-565d-413b-8d26-bd2e2cfa0920</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
